// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolanaMessenger.Infrastructure.EFRepository;

#nullable disable

namespace SolanaMessenger.Infrastructure.PostgresMigrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20251003182809_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolanaMessenger.Domain.Entities.InvalidatedToken", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenID")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("ID");

                    b.HasIndex("TokenID");

                    b.ToTable("InvalidatedTokens");
                });

            modelBuilder.Entity("SolanaMessenger.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("Signatures")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
